name: Sync with upstream
on:
  schedule:
    - cron: '30 22 * * *'
  workflow_dispatch:

jobs:
  merge-upstream:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          fetch-depth: 0
      - name: Sync Repo
        run: gh repo sync ${{ github.repository }} -b main
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
